name: Invitation to the Community
description: I would like to be part of your Organization.
title: "Please invite me to be part of your Community"
labels: [invite me to the organization]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: enter your name here.
    validations:
      required: true
  - type: input
    id: username
    attributes:
      label: GitHub Username
      placeholder: enter your WhatsApp username here.
    validations:
      required: false
  - type: textarea
    id: addcontext
    attributes:
      label: Additional Context
      value: "Where did you find Eduhub? What are your expectations to this community? Why do you want to join Eduhub?"
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Eduhub-Community/Eduhub/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
